export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTH_UPDATE_LOADING = 'SET_AUTH_UPDATE_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const UPDATE_USER = 'UPDATE_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH = 'CLEAR_AUTH';

export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const GET_PROFILE = 'GET_PROFILE';
export const NO_PROFILE_FOUND = 'NO_PROFILE_FOUND';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const SET_USERS_LOADING = 'SET_USERS_LOADING';
export const GET_USERS = 'GET_USERS';
export const LOAD_MORE_USERS = 'LOAD_MORE_USERS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const USERS_ERROR = 'USERS_ERROR';
export const CLEAR_USERS = 'CLEAR_USERS';
export const CLEAR_SEARCH_USERS = 'CLEAR_SEARCH_USERS';
export const SEARCH_NOT_FOUND = 'SEARCH_NOT_FOUND';

export const SET_PHOTO_LOADING = 'SET_PHOTO_LOADING';
export const SET_DP_LOADING = 'SET_DP_LOADING';
export const GET_PHOTOS = 'GET_PHOTOS';
export const SET_PHOTO_MAIN = 'SET_PHOTO_MAIN';
export const UPLOAD_DP = 'UPLOAD_DP';
export const DELETE_PHOTO = 'DELETE_PHOTO';
export const PHOTOS_ERROR = 'PHOTOS_ERROR';
export const CLEAR_PHOTOS = 'CLEAR_PHOTOS';

export const SET_LIKE_LOADING = 'SET_LIKE_LOADING';
export const LIKE_USER = 'LIKE_USER';
export const UNLIKE_USER = 'UNLIKE_USER';
export const GET_LIKERS = 'GET_LIKERS';
export const GET_LIKED = 'GET_LIKED';
export const LIKE_ERROR = 'LIKE_ERROR';
export const CLEAR_LIKE = 'CLEAR_LIKE';

export const SET_MESSAGE_LOADING = 'SET_MESSAGE_LOADING';
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGE_THREAD = 'GET_MESSAGE_THREAD';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_PRIVATE_MESSAGE = 'RECEIVE_PRIVATE_MESSAGE';
export const MESSAGES_ERROR = 'MESSAGES_ERROR';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
